"""add working_dir to pipeline

Revision ID: 0f13e9f2a28d
Revises: f9486768fea8
Create Date: 2026-02-27 14:45:36.512161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f13e9f2a28d'
down_revision: Union[str, Sequence[str], None] = 'f9486768fea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('working_dir', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'working_dir')
    # ### end Alembic commands ###
