"""add step error_message column

Revision ID: 4c32b1b01556
Revises: 8199bcabf466
Create Date: 2026-02-27 18:23:32.086061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c32b1b01556'
down_revision: Union[str, Sequence[str], None] = '8199bcabf466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'error_message')
    # ### end Alembic commands ###
