"""add_prompt_to_pipeline

Revision ID: 9413e90856df
Revises: 84de6aaf4acd
Create Date: 2026-02-27 10:22:15.450525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9413e90856df'
down_revision: Union[str, Sequence[str], None] = '84de6aaf4acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('prompt', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'prompt')
    # ### end Alembic commands ###
